// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicData.proto

#include "PublicData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class PublicData_VectorDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PublicData_Vector> _instance;
} _PublicData_Vector_default_instance_;
class PublicData_PublicTwoMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PublicData_PublicTwoMsg> _instance;
} _PublicData_PublicTwoMsg_default_instance_;
static void InitDefaultsscc_info_PublicData_PublicTwoMsg_PublicData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PublicData_PublicTwoMsg_default_instance_;
    new (ptr) ::PublicData_PublicTwoMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PublicData_PublicTwoMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PublicData_PublicTwoMsg_PublicData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PublicData_PublicTwoMsg_PublicData_2eproto}, {}};

static void InitDefaultsscc_info_PublicData_Vector_PublicData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PublicData_Vector_default_instance_;
    new (ptr) ::PublicData_Vector();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PublicData_Vector::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PublicData_Vector_PublicData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PublicData_Vector_PublicData_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_PublicData_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_PublicData_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_PublicData_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_PublicData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicData_Vector, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PublicData_Vector, x_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicData_PublicTwoMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PublicData_PublicTwoMsg, haa_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PublicData_Vector)},
  { 6, -1, sizeof(::PublicData_PublicTwoMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_PublicData_Vector_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_PublicData_PublicTwoMsg_default_instance_),
};

const char descriptor_table_protodef_PublicData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020PublicData.proto\"\036\n\021PublicData_Vector\022"
  "\t\n\001x\030\001 \001(\002\"&\n\027PublicData_PublicTwoMsg\022\013\n"
  "\003haa\030\001 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_PublicData_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_PublicData_2eproto_sccs[2] = {
  &scc_info_PublicData_PublicTwoMsg_PublicData_2eproto.base,
  &scc_info_PublicData_Vector_PublicData_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_PublicData_2eproto_once;
static bool descriptor_table_PublicData_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicData_2eproto = {
  &descriptor_table_PublicData_2eproto_initialized, descriptor_table_protodef_PublicData_2eproto, "PublicData.proto", 98,
  &descriptor_table_PublicData_2eproto_once, descriptor_table_PublicData_2eproto_sccs, descriptor_table_PublicData_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_PublicData_2eproto::offsets,
  file_level_metadata_PublicData_2eproto, 2, file_level_enum_descriptors_PublicData_2eproto, file_level_service_descriptors_PublicData_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_PublicData_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_PublicData_2eproto)), true);

// ===================================================================

void PublicData_Vector::InitAsDefaultInstance() {
}
class PublicData_Vector::_Internal {
 public:
};

PublicData_Vector::PublicData_Vector()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PublicData_Vector)
}
PublicData_Vector::PublicData_Vector(const PublicData_Vector& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  x_ = from.x_;
  // @@protoc_insertion_point(copy_constructor:PublicData_Vector)
}

void PublicData_Vector::SharedCtor() {
  x_ = 0;
}

PublicData_Vector::~PublicData_Vector() {
  // @@protoc_insertion_point(destructor:PublicData_Vector)
  SharedDtor();
}

void PublicData_Vector::SharedDtor() {
}

void PublicData_Vector::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PublicData_Vector& PublicData_Vector::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PublicData_Vector_PublicData_2eproto.base);
  return *internal_default_instance();
}


void PublicData_Vector::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicData_Vector)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  x_ = 0;
  _internal_metadata_.Clear();
}

const char* PublicData_Vector::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PublicData_Vector::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicData_Vector)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicData_Vector)
  return target;
}

size_t PublicData_Vector::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicData_Vector)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PublicData_Vector::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PublicData_Vector)
  GOOGLE_DCHECK_NE(&from, this);
  const PublicData_Vector* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PublicData_Vector>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PublicData_Vector)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PublicData_Vector)
    MergeFrom(*source);
  }
}

void PublicData_Vector::MergeFrom(const PublicData_Vector& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PublicData_Vector)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.x() <= 0 && from.x() >= 0)) {
    _internal_set_x(from._internal_x());
  }
}

void PublicData_Vector::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PublicData_Vector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublicData_Vector::CopyFrom(const PublicData_Vector& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicData_Vector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicData_Vector::IsInitialized() const {
  return true;
}

void PublicData_Vector::InternalSwap(PublicData_Vector* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicData_Vector::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PublicData_PublicTwoMsg::InitAsDefaultInstance() {
}
class PublicData_PublicTwoMsg::_Internal {
 public:
};

PublicData_PublicTwoMsg::PublicData_PublicTwoMsg()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PublicData_PublicTwoMsg)
}
PublicData_PublicTwoMsg::PublicData_PublicTwoMsg(const PublicData_PublicTwoMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  haa_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_haa().empty()) {
    haa_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.haa_);
  }
  // @@protoc_insertion_point(copy_constructor:PublicData_PublicTwoMsg)
}

void PublicData_PublicTwoMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PublicData_PublicTwoMsg_PublicData_2eproto.base);
  haa_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PublicData_PublicTwoMsg::~PublicData_PublicTwoMsg() {
  // @@protoc_insertion_point(destructor:PublicData_PublicTwoMsg)
  SharedDtor();
}

void PublicData_PublicTwoMsg::SharedDtor() {
  haa_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PublicData_PublicTwoMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PublicData_PublicTwoMsg& PublicData_PublicTwoMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PublicData_PublicTwoMsg_PublicData_2eproto.base);
  return *internal_default_instance();
}


void PublicData_PublicTwoMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicData_PublicTwoMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  haa_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* PublicData_PublicTwoMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string haa = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_haa();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "PublicData_PublicTwoMsg.haa"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PublicData_PublicTwoMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicData_PublicTwoMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string haa = 1;
  if (this->haa().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_haa().data(), static_cast<int>(this->_internal_haa().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicData_PublicTwoMsg.haa");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_haa(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicData_PublicTwoMsg)
  return target;
}

size_t PublicData_PublicTwoMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicData_PublicTwoMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string haa = 1;
  if (this->haa().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_haa());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PublicData_PublicTwoMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PublicData_PublicTwoMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const PublicData_PublicTwoMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PublicData_PublicTwoMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PublicData_PublicTwoMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PublicData_PublicTwoMsg)
    MergeFrom(*source);
  }
}

void PublicData_PublicTwoMsg::MergeFrom(const PublicData_PublicTwoMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PublicData_PublicTwoMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.haa().size() > 0) {

    haa_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.haa_);
  }
}

void PublicData_PublicTwoMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PublicData_PublicTwoMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublicData_PublicTwoMsg::CopyFrom(const PublicData_PublicTwoMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicData_PublicTwoMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicData_PublicTwoMsg::IsInitialized() const {
  return true;
}

void PublicData_PublicTwoMsg::InternalSwap(PublicData_PublicTwoMsg* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  haa_.Swap(&other->haa_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicData_PublicTwoMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PublicData_Vector* Arena::CreateMaybeMessage< ::PublicData_Vector >(Arena* arena) {
  return Arena::CreateInternal< ::PublicData_Vector >(arena);
}
template<> PROTOBUF_NOINLINE ::PublicData_PublicTwoMsg* Arena::CreateMaybeMessage< ::PublicData_PublicTwoMsg >(Arena* arena) {
  return Arena::CreateInternal< ::PublicData_PublicTwoMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
