// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PublicData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PublicData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PublicData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicData_2eproto;
class PublicData_PublicTwoMsg;
class PublicData_PublicTwoMsgDefaultTypeInternal;
extern PublicData_PublicTwoMsgDefaultTypeInternal _PublicData_PublicTwoMsg_default_instance_;
class PublicData_Vector;
class PublicData_VectorDefaultTypeInternal;
extern PublicData_VectorDefaultTypeInternal _PublicData_Vector_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PublicData_PublicTwoMsg* Arena::CreateMaybeMessage<::PublicData_PublicTwoMsg>(Arena*);
template<> ::PublicData_Vector* Arena::CreateMaybeMessage<::PublicData_Vector>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PublicData_Vector :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicData_Vector) */ {
 public:
  PublicData_Vector();
  virtual ~PublicData_Vector();

  PublicData_Vector(const PublicData_Vector& from);
  PublicData_Vector(PublicData_Vector&& from) noexcept
    : PublicData_Vector() {
    *this = ::std::move(from);
  }

  inline PublicData_Vector& operator=(const PublicData_Vector& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicData_Vector& operator=(PublicData_Vector&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PublicData_Vector& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PublicData_Vector* internal_default_instance() {
    return reinterpret_cast<const PublicData_Vector*>(
               &_PublicData_Vector_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PublicData_Vector& a, PublicData_Vector& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicData_Vector* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PublicData_Vector* New() const final {
    return CreateMaybeMessage<PublicData_Vector>(nullptr);
  }

  PublicData_Vector* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PublicData_Vector>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PublicData_Vector& from);
  void MergeFrom(const PublicData_Vector& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicData_Vector* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicData_Vector";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PublicData_2eproto);
    return ::descriptor_table_PublicData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // @@protoc_insertion_point(class_scope:PublicData_Vector)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PublicData_2eproto;
};
// -------------------------------------------------------------------

class PublicData_PublicTwoMsg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicData_PublicTwoMsg) */ {
 public:
  PublicData_PublicTwoMsg();
  virtual ~PublicData_PublicTwoMsg();

  PublicData_PublicTwoMsg(const PublicData_PublicTwoMsg& from);
  PublicData_PublicTwoMsg(PublicData_PublicTwoMsg&& from) noexcept
    : PublicData_PublicTwoMsg() {
    *this = ::std::move(from);
  }

  inline PublicData_PublicTwoMsg& operator=(const PublicData_PublicTwoMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicData_PublicTwoMsg& operator=(PublicData_PublicTwoMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PublicData_PublicTwoMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PublicData_PublicTwoMsg* internal_default_instance() {
    return reinterpret_cast<const PublicData_PublicTwoMsg*>(
               &_PublicData_PublicTwoMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PublicData_PublicTwoMsg& a, PublicData_PublicTwoMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicData_PublicTwoMsg* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PublicData_PublicTwoMsg* New() const final {
    return CreateMaybeMessage<PublicData_PublicTwoMsg>(nullptr);
  }

  PublicData_PublicTwoMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PublicData_PublicTwoMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PublicData_PublicTwoMsg& from);
  void MergeFrom(const PublicData_PublicTwoMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicData_PublicTwoMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicData_PublicTwoMsg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PublicData_2eproto);
    return ::descriptor_table_PublicData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHaaFieldNumber = 1,
  };
  // string haa = 1;
  void clear_haa();
  const std::string& haa() const;
  void set_haa(const std::string& value);
  void set_haa(std::string&& value);
  void set_haa(const char* value);
  void set_haa(const char* value, size_t size);
  std::string* mutable_haa();
  std::string* release_haa();
  void set_allocated_haa(std::string* haa);
  private:
  const std::string& _internal_haa() const;
  void _internal_set_haa(const std::string& value);
  std::string* _internal_mutable_haa();
  public:

  // @@protoc_insertion_point(class_scope:PublicData_PublicTwoMsg)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr haa_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PublicData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PublicData_Vector

// float x = 1;
inline void PublicData_Vector::clear_x() {
  x_ = 0;
}
inline float PublicData_Vector::_internal_x() const {
  return x_;
}
inline float PublicData_Vector::x() const {
  // @@protoc_insertion_point(field_get:PublicData_Vector.x)
  return _internal_x();
}
inline void PublicData_Vector::_internal_set_x(float value) {
  
  x_ = value;
}
inline void PublicData_Vector::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:PublicData_Vector.x)
}

// -------------------------------------------------------------------

// PublicData_PublicTwoMsg

// string haa = 1;
inline void PublicData_PublicTwoMsg::clear_haa() {
  haa_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PublicData_PublicTwoMsg::haa() const {
  // @@protoc_insertion_point(field_get:PublicData_PublicTwoMsg.haa)
  return _internal_haa();
}
inline void PublicData_PublicTwoMsg::set_haa(const std::string& value) {
  _internal_set_haa(value);
  // @@protoc_insertion_point(field_set:PublicData_PublicTwoMsg.haa)
}
inline std::string* PublicData_PublicTwoMsg::mutable_haa() {
  // @@protoc_insertion_point(field_mutable:PublicData_PublicTwoMsg.haa)
  return _internal_mutable_haa();
}
inline const std::string& PublicData_PublicTwoMsg::_internal_haa() const {
  return haa_.GetNoArena();
}
inline void PublicData_PublicTwoMsg::_internal_set_haa(const std::string& value) {
  
  haa_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PublicData_PublicTwoMsg::set_haa(std::string&& value) {
  
  haa_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PublicData_PublicTwoMsg.haa)
}
inline void PublicData_PublicTwoMsg::set_haa(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  haa_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PublicData_PublicTwoMsg.haa)
}
inline void PublicData_PublicTwoMsg::set_haa(const char* value, size_t size) {
  
  haa_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PublicData_PublicTwoMsg.haa)
}
inline std::string* PublicData_PublicTwoMsg::_internal_mutable_haa() {
  
  return haa_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PublicData_PublicTwoMsg::release_haa() {
  // @@protoc_insertion_point(field_release:PublicData_PublicTwoMsg.haa)
  
  return haa_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PublicData_PublicTwoMsg::set_allocated_haa(std::string* haa) {
  if (haa != nullptr) {
    
  } else {
    
  }
  haa_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), haa);
  // @@protoc_insertion_point(field_set_allocated:PublicData_PublicTwoMsg.haa)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PublicData_2eproto
