# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProtoUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 788)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MsgTreeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.MsgTreeWidget.setGeometry(QtCore.QRect(20, 60, 541, 671))
        self.MsgTreeWidget.setObjectName("MsgTreeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.MsgTreeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.MsgTreeWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(580, 330, 411, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CbxValueType = QtWidgets.QComboBox(self.frame)
        self.CbxValueType.setGeometry(QtCore.QRect(20, 150, 171, 31))
        self.CbxValueType.setObjectName("CbxValueType")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 81, 16))
        self.label_3.setObjectName("label_3")
        self.BtnField = QtWidgets.QPushButton(self.frame)
        self.BtnField.setGeometry(QtCore.QRect(20, 340, 81, 41))
        self.BtnField.setObjectName("BtnField")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 91, 21))
        self.label_2.setObjectName("label_2")
        self.LetFieldName = QtWidgets.QLineEdit(self.frame)
        self.LetFieldName.setGeometry(QtCore.QRect(20, 240, 181, 31))
        self.LetFieldName.setObjectName("LetFieldName")
        self.CbxProtoType = QtWidgets.QComboBox(self.frame)
        self.CbxProtoType.setGeometry(QtCore.QRect(20, 60, 171, 31))
        self.CbxProtoType.setObjectName("CbxProtoType")
        self.CbxProtoType.addItem("")
        self.CbxProtoType.addItem("")
        self.CbxProtoType.addItem("")
        self.BtnFieldCancel = QtWidgets.QPushButton(self.frame)
        self.BtnFieldCancel.setGeometry(QtCore.QRect(130, 340, 81, 41))
        self.BtnFieldCancel.setObjectName("BtnFieldCancel")
        self.LbMsgField = QtWidgets.QLabel(self.frame)
        self.LbMsgField.setGeometry(QtCore.QRect(20, 290, 361, 41))
        self.LbMsgField.setFrameShape(QtWidgets.QFrame.Box)
        self.LbMsgField.setObjectName("LbMsgField")
        self.BtnReq = QtWidgets.QRadioButton(self.centralwidget)
        self.BtnReq.setGeometry(QtCore.QRect(610, 60, 81, 41))
        self.BtnReq.setObjectName("BtnReq")
        self.BtnNotice = QtWidgets.QRadioButton(self.centralwidget)
        self.BtnNotice.setGeometry(QtCore.QRect(790, 70, 89, 21))
        self.BtnNotice.setObjectName("BtnNotice")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 131, 81, 31))
        self.label_5.setObjectName("label_5")
        self.LetMsgName = QtWidgets.QLineEdit(self.centralwidget)
        self.LetMsgName.setGeometry(QtCore.QRect(670, 130, 221, 31))
        self.LetMsgName.setObjectName("LetMsgName")
        self.BtnMsg = QtWidgets.QPushButton(self.centralwidget)
        self.BtnMsg.setGeometry(QtCore.QRect(610, 190, 111, 41))
        self.BtnMsg.setObjectName("BtnMsg")
        self.BtnMsgCancel = QtWidgets.QPushButton(self.centralwidget)
        self.BtnMsgCancel.setGeometry(QtCore.QRect(760, 190, 121, 41))
        self.BtnMsgCancel.setObjectName("BtnMsgCancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menutool = QtWidgets.QMenu(self.menubar)
        self.menutool.setObjectName("menutool")
        self.menuProto = QtWidgets.QMenu(self.menutool)
        self.menuProto.setObjectName("menuProto")
        self.menuTable = QtWidgets.QMenu(self.menutool)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menuOpen = QtWidgets.QAction(MainWindow)
        self.menuOpen.setObjectName("menuOpen")
        self.menuRecentOen = QtWidgets.QAction(MainWindow)
        self.menuRecentOen.setObjectName("menuRecentOen")
        self.menuSave = QtWidgets.QAction(MainWindow)
        self.menuSave.setObjectName("menuSave")
        self.menuClose = QtWidgets.QAction(MainWindow)
        self.menuClose.setObjectName("menuClose")
        self.menuSaveAs = QtWidgets.QAction(MainWindow)
        self.menuSaveAs.setObjectName("menuSaveAs")
        self.menuProtoServer = QtWidgets.QAction(MainWindow)
        self.menuProtoServer.setObjectName("menuProtoServer")
        self.menuProtoClient = QtWidgets.QAction(MainWindow)
        self.menuProtoClient.setObjectName("menuProtoClient")
        self.menuTableServer = QtWidgets.QAction(MainWindow)
        self.menuTableServer.setObjectName("menuTableServer")
        self.menuTableClient = QtWidgets.QAction(MainWindow)
        self.menuTableClient.setObjectName("menuTableClient")
        self.menu_setting = QtWidgets.QAction(MainWindow)
        self.menu_setting.setObjectName("menu_setting")
        self.menu.addAction(self.menuOpen)
        self.menu.addAction(self.menuRecentOen)
        self.menu.addSeparator()
        self.menu.addAction(self.menuSave)
        self.menu.addAction(self.menuSaveAs)
        self.menu.addAction(self.menuClose)
        self.menuProto.addAction(self.menuProtoServer)
        self.menuProto.addSeparator()
        self.menuProto.addAction(self.menuProtoClient)
        self.menuTable.addAction(self.menuTableServer)
        self.menuTable.addSeparator()
        self.menuTable.addAction(self.menuTableClient)
        self.menutool.addAction(self.menuProto.menuAction())
        self.menutool.addAction(self.menuTable.menuAction())
        self.menutool.addSeparator()
        self.menutool.addAction(self.menu_setting)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menutool.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动化工具"))
        self.MsgTreeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.MsgTreeWidget.isSortingEnabled()
        self.MsgTreeWidget.setSortingEnabled(False)
        self.MsgTreeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "aaa"))
        self.MsgTreeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "bbbb"))
        self.MsgTreeWidget.setSortingEnabled(__sortingEnabled)
        self.CbxValueType.setItemText(0, _translate("MainWindow", "int32"))
        self.CbxValueType.setItemText(1, _translate("MainWindow", "int64"))
        self.CbxValueType.setItemText(2, _translate("MainWindow", "string"))
        self.CbxValueType.setItemText(3, _translate("MainWindow", "float"))
        self.CbxValueType.setItemText(4, _translate("MainWindow", "double"))
        self.CbxValueType.setItemText(5, _translate("MainWindow", "bytes"))
        self.CbxValueType.setItemText(6, _translate("MainWindow", "bool"))
        self.CbxValueType.setItemText(7, _translate("MainWindow", "uint32"))
        self.CbxValueType.setItemText(8, _translate("MainWindow", "uint64"))
        self.label.setText(_translate("MainWindow", "proto可选类型"))
        self.label_3.setText(_translate("MainWindow", "字段名称"))
        self.BtnField.setText(_translate("MainWindow", "确定"))
        self.label_2.setText(_translate("MainWindow", "数据类型"))
        self.CbxProtoType.setItemText(0, _translate("MainWindow", "optional"))
        self.CbxProtoType.setItemText(1, _translate("MainWindow", "required"))
        self.CbxProtoType.setItemText(2, _translate("MainWindow", "repeated"))
        self.BtnFieldCancel.setText(_translate("MainWindow", "取消"))
        self.LbMsgField.setText(_translate("MainWindow", "TextLabel"))
        self.BtnReq.setText(_translate("MainWindow", "请求消息"))
        self.BtnNotice.setText(_translate("MainWindow", "通知消息"))
        self.label_5.setText(_translate("MainWindow", "消息名称："))
        self.BtnMsg.setText(_translate("MainWindow", "确定"))
        self.BtnMsgCancel.setText(_translate("MainWindow", "取消"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menutool.setTitle(_translate("MainWindow", "工具"))
        self.menuProto.setTitle(_translate("MainWindow", "导出协议"))
        self.menuTable.setTitle(_translate("MainWindow", "导出数据表"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.menuOpen.setText(_translate("MainWindow", "打开"))
        self.menuOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.menuRecentOen.setText(_translate("MainWindow", "最近打开"))
        self.menuRecentOen.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.menuSave.setText(_translate("MainWindow", "保存"))
        self.menuSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuClose.setText(_translate("MainWindow", "关闭"))
        self.menuSaveAs.setText(_translate("MainWindow", "另存为..."))
        self.menuSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.menuProtoServer.setText(_translate("MainWindow", "服务器协议"))
        self.menuProtoServer.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.menuProtoClient.setText(_translate("MainWindow", "客户端协议"))
        self.menuProtoClient.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.menuTableServer.setText(_translate("MainWindow", "服务器"))
        self.menuTableServer.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.menuTableClient.setText(_translate("MainWindow", "客户端"))
        self.menuTableClient.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.menu_setting.setText(_translate("MainWindow", "选项"))
        self.menu_setting.setShortcut(_translate("MainWindow", "Ctrl+T"))
