# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Designer/tool.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 776)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.WidMsgTree = QtWidgets.QTreeWidget(self.centralwidget)
        self.WidMsgTree.setGeometry(QtCore.QRect(10, 70, 491, 651))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.WidMsgTree.setFont(font)
        self.WidMsgTree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.WidMsgTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.WidMsgTree.setAutoScroll(False)
        self.WidMsgTree.setAutoExpandDelay(-1)
        self.WidMsgTree.setIndentation(10)
        self.WidMsgTree.setColumnCount(4)
        self.WidMsgTree.setObjectName("WidMsgTree")
        self.WidMsgTree.headerItem().setText(0, "1")
        self.WidMsgTree.headerItem().setText(1, "2")
        self.WidMsgTree.headerItem().setText(2, "3")
        self.WidMsgTree.headerItem().setText(3, "4")
        self.WidMsgTree.header().setDefaultSectionSize(280)
        self.FrameMsg = QtWidgets.QFrame(self.centralwidget)
        self.FrameMsg.setGeometry(QtCore.QRect(630, 10, 191, 171))
        self.FrameMsg.setAutoFillBackground(True)
        self.FrameMsg.setStyleSheet("")
        self.FrameMsg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameMsg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FrameMsg.setLineWidth(2)
        self.FrameMsg.setMidLineWidth(2)
        self.FrameMsg.setObjectName("FrameMsg")
        self.BtnReq = QtWidgets.QRadioButton(self.FrameMsg)
        self.BtnReq.setGeometry(QtCore.QRect(10, 0, 81, 41))
        self.BtnReq.setObjectName("BtnReq")
        self.BtnNotify = QtWidgets.QRadioButton(self.FrameMsg)
        self.BtnNotify.setGeometry(QtCore.QRect(110, 10, 89, 21))
        self.BtnNotify.setObjectName("BtnNotify")
        self.label_5 = QtWidgets.QLabel(self.FrameMsg)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.FrameMsg)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 61, 31))
        self.label_10.setObjectName("label_10")
        self.LetMsgCmt = QtWidgets.QLineEdit(self.FrameMsg)
        self.LetMsgCmt.setGeometry(QtCore.QRect(70, 90, 111, 31))
        self.LetMsgCmt.setObjectName("LetMsgCmt")
        self.LetMsgName = QtWidgets.QLineEdit(self.FrameMsg)
        self.LetMsgName.setGeometry(QtCore.QRect(70, 50, 111, 31))
        self.LetMsgName.setObjectName("LetMsgName")
        self.BtnMsgAdd = QtWidgets.QPushButton(self.FrameMsg)
        self.BtnMsgAdd.setGeometry(QtCore.QRect(60, 130, 71, 31))
        self.BtnMsgAdd.setObjectName("BtnMsgAdd")
        self.BtnDel = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDel.setGeometry(QtCore.QRect(520, 140, 81, 41))
        self.BtnDel.setObjectName("BtnDel")
        self.BtnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.BtnUpdate.setGeometry(QtCore.QRect(520, 240, 81, 41))
        self.BtnUpdate.setObjectName("BtnUpdate")
        self.BtnSave = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSave.setGeometry(QtCore.QRect(520, 340, 81, 41))
        self.BtnSave.setObjectName("BtnSave")
        self.FrameMod = QtWidgets.QFrame(self.centralwidget)
        self.FrameMod.setGeometry(QtCore.QRect(10, 10, 491, 51))
        self.FrameMod.setAutoFillBackground(True)
        self.FrameMod.setStyleSheet("")
        self.FrameMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameMod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FrameMod.setLineWidth(2)
        self.FrameMod.setMidLineWidth(2)
        self.FrameMod.setObjectName("FrameMod")
        self.label_6 = QtWidgets.QLabel(self.FrameMod)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.label_6.setObjectName("label_6")
        self.LetModName = QtWidgets.QLineEdit(self.FrameMod)
        self.LetModName.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.LetModName.setObjectName("LetModName")
        self.label_7 = QtWidgets.QLabel(self.FrameMod)
        self.label_7.setGeometry(QtCore.QRect(190, 10, 51, 21))
        self.label_7.setObjectName("label_7")
        self.LetModCmt = QtWidgets.QLineEdit(self.FrameMod)
        self.LetModCmt.setGeometry(QtCore.QRect(240, 10, 161, 31))
        self.LetModCmt.setObjectName("LetModCmt")
        self.BtnModAdd = QtWidgets.QPushButton(self.FrameMod)
        self.BtnModAdd.setGeometry(QtCore.QRect(410, 10, 71, 31))
        self.BtnModAdd.setObjectName("BtnModAdd")
        self.BbvInfo = QtWidgets.QTableView(self.centralwidget)
        self.BbvInfo.setGeometry(QtCore.QRect(520, 530, 301, 191))
        self.BbvInfo.setObjectName("BbvInfo")
        self.FrameField = QtWidgets.QFrame(self.centralwidget)
        self.FrameField.setGeometry(QtCore.QRect(630, 190, 191, 331))
        self.FrameField.setAutoFillBackground(True)
        self.FrameField.setStyleSheet("")
        self.FrameField.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameField.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FrameField.setLineWidth(2)
        self.FrameField.setMidLineWidth(2)
        self.FrameField.setObjectName("FrameField")
        self.CbxValueType = QtWidgets.QComboBox(self.FrameField)
        self.CbxValueType.setGeometry(QtCore.QRect(10, 120, 171, 31))
        self.CbxValueType.setObjectName("CbxValueType")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.CbxValueType.addItem("")
        self.label = QtWidgets.QLabel(self.FrameField)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.FrameField)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 81, 16))
        self.label_3.setObjectName("label_3")
        self.BtnFieldAdd = QtWidgets.QPushButton(self.FrameField)
        self.BtnFieldAdd.setGeometry(QtCore.QRect(50, 280, 81, 41))
        self.BtnFieldAdd.setObjectName("BtnFieldAdd")
        self.label_2 = QtWidgets.QLabel(self.FrameField)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_2.setObjectName("label_2")
        self.LetFieldName = QtWidgets.QLineEdit(self.FrameField)
        self.LetFieldName.setGeometry(QtCore.QRect(10, 180, 171, 31))
        self.LetFieldName.setObjectName("LetFieldName")
        self.CbxProtoType = QtWidgets.QComboBox(self.FrameField)
        self.CbxProtoType.setGeometry(QtCore.QRect(10, 50, 171, 31))
        self.CbxProtoType.setObjectName("CbxProtoType")
        self.CbxProtoType.addItem("")
        self.CbxProtoType.addItem("")
        self.CbxProtoType.addItem("")
        self.LetFieldCmt = QtWidgets.QLineEdit(self.FrameField)
        self.LetFieldCmt.setGeometry(QtCore.QRect(10, 240, 171, 31))
        self.LetFieldCmt.setObjectName("LetFieldCmt")
        self.label_4 = QtWidgets.QLabel(self.FrameField)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 81, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuProto = QtWidgets.QMenu(self.menuTool)
        self.menuProto.setObjectName("menuProto")
        self.menuSet = QtWidgets.QMenu(self.menubar)
        self.menuSet.setObjectName("menuSet")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menuOpen = QtWidgets.QAction(MainWindow)
        self.menuOpen.setObjectName("menuOpen")
        self.menuRecentOen = QtWidgets.QAction(MainWindow)
        self.menuRecentOen.setObjectName("menuRecentOen")
        self.menuSave = QtWidgets.QAction(MainWindow)
        self.menuSave.setObjectName("menuSave")
        self.menuClose = QtWidgets.QAction(MainWindow)
        self.menuClose.setObjectName("menuClose")
        self.menuSaveAs = QtWidgets.QAction(MainWindow)
        self.menuSaveAs.setObjectName("menuSaveAs")
        self.menuProtoServer = QtWidgets.QAction(MainWindow)
        self.menuProtoServer.setObjectName("menuProtoServer")
        self.menuProtoClient = QtWidgets.QAction(MainWindow)
        self.menuProtoClient.setObjectName("menuProtoClient")
        self.menuTableServer = QtWidgets.QAction(MainWindow)
        self.menuTableServer.setObjectName("menuTableServer")
        self.menuTableClient = QtWidgets.QAction(MainWindow)
        self.menuTableClient.setObjectName("menuTableClient")
        self.menuTable = QtWidgets.QAction(MainWindow)
        self.menuTable.setObjectName("menuTable")
        self.menuSetting = QtWidgets.QAction(MainWindow)
        self.menuSetting.setObjectName("menuSetting")
        self.menuFile.addAction(self.menuOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave)
        self.menuFile.addAction(self.menuSaveAs)
        self.menuFile.addAction(self.menuClose)
        self.menuProto.addAction(self.menuProtoServer)
        self.menuProto.addSeparator()
        self.menuProto.addAction(self.menuProtoClient)
        self.menuTool.addAction(self.menuProto.menuAction())
        self.menuTool.addAction(self.menuTable)
        self.menuTool.addSeparator()
        self.menuSet.addAction(self.menuSetting)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuSet.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动化工具"))
        self.WidMsgTree.setSortingEnabled(False)
        self.BtnReq.setText(_translate("MainWindow", "请求消息"))
        self.BtnNotify.setText(_translate("MainWindow", "通知消息"))
        self.label_5.setText(_translate("MainWindow", "消息名称"))
        self.label_10.setText(_translate("MainWindow", "消息说明"))
        self.BtnMsgAdd.setText(_translate("MainWindow", "确定"))
        self.BtnDel.setText(_translate("MainWindow", "删除"))
        self.BtnUpdate.setText(_translate("MainWindow", "修改"))
        self.BtnSave.setText(_translate("MainWindow", "保存"))
        self.label_6.setText(_translate("MainWindow", "模块名称"))
        self.label_7.setText(_translate("MainWindow", "模块说明"))
        self.BtnModAdd.setText(_translate("MainWindow", "添加新模块"))
        self.CbxValueType.setItemText(0, _translate("MainWindow", "int32"))
        self.CbxValueType.setItemText(1, _translate("MainWindow", "int64"))
        self.CbxValueType.setItemText(2, _translate("MainWindow", "string"))
        self.CbxValueType.setItemText(3, _translate("MainWindow", "float"))
        self.CbxValueType.setItemText(4, _translate("MainWindow", "double"))
        self.CbxValueType.setItemText(5, _translate("MainWindow", "bytes"))
        self.CbxValueType.setItemText(6, _translate("MainWindow", "bool"))
        self.CbxValueType.setItemText(7, _translate("MainWindow", "uint32"))
        self.CbxValueType.setItemText(8, _translate("MainWindow", "uint64"))
        self.label.setText(_translate("MainWindow", "proto可选类型"))
        self.label_3.setText(_translate("MainWindow", "字段名称"))
        self.BtnFieldAdd.setText(_translate("MainWindow", "确定"))
        self.label_2.setText(_translate("MainWindow", "数据类型"))
        self.CbxProtoType.setItemText(0, _translate("MainWindow", "optional"))
        self.CbxProtoType.setItemText(1, _translate("MainWindow", "required"))
        self.CbxProtoType.setItemText(2, _translate("MainWindow", "repeated"))
        self.label_4.setText(_translate("MainWindow", "字段说明"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuTool.setTitle(_translate("MainWindow", "工具"))
        self.menuProto.setTitle(_translate("MainWindow", "导出协议"))
        self.menuSet.setTitle(_translate("MainWindow", "设置"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.menuOpen.setText(_translate("MainWindow", "打开"))
        self.menuOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.menuRecentOen.setText(_translate("MainWindow", "最近打开"))
        self.menuRecentOen.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.menuSave.setText(_translate("MainWindow", "保存"))
        self.menuSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuClose.setText(_translate("MainWindow", "关闭"))
        self.menuSaveAs.setText(_translate("MainWindow", "另存为..."))
        self.menuSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.menuProtoServer.setText(_translate("MainWindow", "服务器协议"))
        self.menuProtoServer.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.menuProtoClient.setText(_translate("MainWindow", "客户端协议"))
        self.menuProtoClient.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.menuTableServer.setText(_translate("MainWindow", "服务器"))
        self.menuTableServer.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.menuTableClient.setText(_translate("MainWindow", "客户端"))
        self.menuTableClient.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.menuTable.setText(_translate("MainWindow", "导出数据表"))
        self.menuSetting.setText(_translate("MainWindow", "设置选项"))
