# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Designer/setting.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName("SettingWindow")
        SettingWindow.resize(532, 436)
        self.centralwidget = QtWidgets.QWidget(SettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 101, 21))
        self.label.setObjectName("label")
        self.letMsgPath = QtWidgets.QLineEdit(self.centralwidget)
        self.letMsgPath.setGeometry(QtCore.QRect(40, 40, 381, 31))
        self.letMsgPath.setReadOnly(True)
        self.letMsgPath.setObjectName("letMsgPath")
        self.btnMsg = QtWidgets.QPushButton(self.centralwidget)
        self.btnMsg.setGeometry(QtCore.QRect(450, 40, 51, 31))
        self.btnMsg.setObjectName("btnMsg")
        self.btnProtobuf = QtWidgets.QPushButton(self.centralwidget)
        self.btnProtobuf.setGeometry(QtCore.QRect(450, 180, 51, 31))
        self.btnProtobuf.setObjectName("btnProtobuf")
        self.letProtobufPath = QtWidgets.QLineEdit(self.centralwidget)
        self.letProtobufPath.setGeometry(QtCore.QRect(40, 180, 381, 31))
        self.letProtobufPath.setReadOnly(True)
        self.letProtobufPath.setObjectName("letProtobufPath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 101, 21))
        self.label_2.setObjectName("label_2")
        self.btnExcel = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcel.setGeometry(QtCore.QRect(450, 250, 51, 31))
        self.btnExcel.setObjectName("btnExcel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 101, 21))
        self.label_3.setObjectName("label_3")
        self.letExcelPath = QtWidgets.QLineEdit(self.centralwidget)
        self.letExcelPath.setGeometry(QtCore.QRect(40, 250, 381, 31))
        self.letExcelPath.setReadOnly(True)
        self.letExcelPath.setObjectName("letExcelPath")
        self.btnProto = QtWidgets.QPushButton(self.centralwidget)
        self.btnProto.setGeometry(QtCore.QRect(450, 110, 51, 31))
        self.btnProto.setObjectName("btnProto")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 121, 21))
        self.label_4.setObjectName("label_4")
        self.letProtoPath = QtWidgets.QLineEdit(self.centralwidget)
        self.letProtoPath.setGeometry(QtCore.QRect(40, 110, 381, 31))
        self.letProtoPath.setReadOnly(True)
        self.letProtoPath.setObjectName("letProtoPath")
        self.letJsonPath = QtWidgets.QLineEdit(self.centralwidget)
        self.letJsonPath.setGeometry(QtCore.QRect(40, 320, 381, 31))
        self.letJsonPath.setReadOnly(True)
        self.letJsonPath.setObjectName("letJsonPath")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 290, 101, 21))
        self.label_5.setObjectName("label_5")
        self.btnJson = QtWidgets.QPushButton(self.centralwidget)
        self.btnJson.setGeometry(QtCore.QRect(450, 320, 51, 31))
        self.btnJson.setObjectName("btnJson")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 360, 121, 21))
        self.label_6.setObjectName("label_6")
        self.btnExcelCode = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcelCode.setGeometry(QtCore.QRect(450, 390, 51, 31))
        self.btnExcelCode.setObjectName("btnExcelCode")
        self.letExcelCodePath = QtWidgets.QLineEdit(self.centralwidget)
        self.letExcelCodePath.setGeometry(QtCore.QRect(40, 390, 381, 31))
        self.letExcelCodePath.setReadOnly(True)
        self.letExcelCodePath.setObjectName("letExcelCodePath")
        SettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingWindow.setWindowTitle(_translate("SettingWindow", "设置"))
        self.label.setText(_translate("SettingWindow", "消息加载路径："))
        self.btnMsg.setText(_translate("SettingWindow", "..."))
        self.btnProtobuf.setText(_translate("SettingWindow", "..."))
        self.label_2.setText(_translate("SettingWindow", "导出协议路径："))
        self.btnExcel.setText(_translate("SettingWindow", "..."))
        self.label_3.setText(_translate("SettingWindow", "excel表路径："))
        self.btnProto.setText(_translate("SettingWindow", "..."))
        self.label_4.setText(_translate("SettingWindow", "proto文件保存路径："))
        self.label_5.setText(_translate("SettingWindow", "导出表路径："))
        self.btnJson.setText(_translate("SettingWindow", "..."))
        self.label_6.setText(_translate("SettingWindow", "导出表结构代码路径："))
        self.btnExcelCode.setText(_translate("SettingWindow", "..."))
